### ISSUE TITLE
missing directories: tests failing in master

### ISSUE THREAD

**Issue by Chrism7** [nils-wisiol/pypuf#117]
I just found out (with help from @nils-wisiol ) that the unit-tests on a local master branch are failing. The cause is the absence of 2 directories which are not being created when pulling the master branch.
The directories are .../pypuf/test/**test** and .../pypuf/test/test/**logs**.

**Comment by nils-wisiol** [comment]
the link is dead :-(

**Comment by Chrism7** [comment]
https://github.com/nils-wisiol/pypuf/commit/458772c

**Comment by nils-wisiol** [comment]
the commit adds the directory by adding a `.gitignore` file inside it (that's standard procedure for adding directories to version control)
