### ISSUE TITLE
Experimenter does not print exception traceback

### ISSUE THREAD

**Issue by benj-zen** [nils-wisiol/pypuf#130]
When an exception occurs in an experiment the traceback should be printed. However, this line seems not to be working:
https://github.com/nils-wisiol/pypuf/blob/d4c0dbffd552eec76436b7f58b668f60c83f36ed/pypuf/experiments/experimenter.py#L154

Maybe it's because it's not directly in an except block.

**Comment by nils-wisiol** [comment]
A quick and dirty way to obtain the traceback is to re-raise that exception

**Comment by benj-zen** [comment]
I replaced the line with
`traceback.print_exception(type(exception), exception, exception.__traceback__, file=sys.stderr)`
in my current working branch which seems to be working.

**Comment by benj-zen** [comment]
Possible fix in e00cc97986a5b6ee25a0754e307bc0ad16504157

**Comment by nils-wisiol** [comment]
#135

**Comment by nils-wisiol** [comment]
Fixed via #135, thanks!
