### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by MrM0nkey** [nils-wisiol/pypuf#14]
In order to increase credibility of this project it is important to enhance the traceability.
I suggest to write:
-  [x] A better README.md which shows the purpose about the project.
-  [ ] a user guide (Wiki)
-  [ ] a developer guide (Wiki)
-  [x] contributing guidelines (CONTRIBUTING.md)
-  [x] a summary for each learning algorithm (Wiki)
-  [x] a summary for each puf simulation model (Wiki)
-  [x] comments in code

**Comment by nils-wisiol** [comment]
README.md was added per #18 
Contribution is mentioned in README.md for now. We can create CONTRIBUTING.md once there is more rules.
For the summaries of learning and simulation, please refer to the pypuf paper.
Comments in the code are added.
