### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by samehkhalfaoui** [nils-wisiol/pypuf#159]
Hey, first of all, thank you for this amazing work ! 
I am looking forward to using your XOR Arbiter Puf simulator to generate some challenge/response pairs. However, i have seen the documentation in  [link](https://pypuf.readthedocs.io/en/latest/simulation/overview.html) and i have noticed that the libraries have been changed. I cannot use the following example since the module pypuf.simulation is not found.  
>>> from pypuf.simulation.delay import XORArbiterPUF
>>> puf = XORArbiterPUF(n=64, k=2, seed=1) 

Could you provide me with an up-to-date documentation that i can use for my experiments using your simulator ? Thank you very much !

**Comment by nils-wisiol** [comment]
Please install pypuf using `pip` or use the version from the `v2` branch. The current `master` branch is to be archived soon.

**Comment by nils-wisiol** [comment]
pypuf version 2 is now published on pypi and also the default on GitHub. The DOI for citations changed in the process.

**Comment by maskof** [comment]
Thanks for the update but what have changed exactly in comparison with the v2 branch ?

**Comment by nils-wisiol** [comment]
Please check the commit log at https://github.com/nils-wisiol/pypuf/commits/main

You can find each version in there with the commit message "release version ..." and then see which new commits followed. Of course, you can also find the differences of each version by looking at the `v2.0.0` tag in the git history and compare it to, say, `v0.0.8`.
