### ISSUE TITLE
XOR Arbiter PUFs are not biased by default. 

### ISSUE THREAD

**Issue by RRasche** [nils-wisiol/pypuf#165]
If a normal XOR Arbiter PUF is called, it is initialized without a bias, which leads to the response of challenge being 100% correlated to a response of a challenge with the last bit flipped (for Arbiter PUFs with an even number of XORs the responses is the same and the response flips)

A small program to test this behaviour (tested with pypuf 2.3.0):

```python
from pypuf.simulation.delay import XORArbiterPUF
from pypuf.io import random_inputs

import numpy as np
from matplotlib import pyplot as py
import os


n = 64
numbTries = 100000

sum = 0
nnMat = np.ones((2, n))
nnMat[1, -1] = -1
nnMat = np.tile(nnMat, (numbTries, 1))


puf = XORArbiterPUF(n, 100, int.from_bytes(os.urandom(4), "big"))
x = random_inputs(n, numbTries, int.from_bytes(os.urandom(4), "big"))

xv = np.repeat(x, 2, axis=0)
xv =  xv * nnMat


PufSample = puf.eval(xv)
print(np.sum(PufSample[::2] - PufSample[1::2])) #outputs 0.0


puf = XORArbiterPUF(n, 101, int.from_bytes(os.urandom(4), "big"))
x = random_inputs(n, numbTries, int.from_bytes(os.urandom(4), "big"))

xv = np.repeat(x, 2, axis=0)
xv =  xv * nnMat

PufSample = puf.eval(xv)
print(np.sum(PufSample[::2] + PufSample[1::2])) #outputs 0.0
```

As a workaround one could set 
`puf.weight_array[:,-1] = np.random.normal(loc = 0, scale = 1, size=len(puf.weight_array))`
if the numpy seed has been set beforehand. That way the problem does no longer exist, but I'm not sure if the bias should have the same scale as the weights.

**Comment by nils-wisiol** [comment]
This makes a breaking change necessary. I'll use the opportunity to choose the weights according to what's written in https://ia.cr/2021/555, Appendix A, Corollary 1, i.e. choosing the weight vector w for an Arbiter PUF by:

- w[0] with scale 1
- w[i] with scale 2 for 1 <= i <= n
- b with scale 1

**Comment by RRasche** [comment]
The original problem has been solved with this. The only thing, that I could think about, that hasn't been solved, are the ff loops for the feed forward PUFs, but I think you already seen and commented that in the code.

I did some (crude) statistical test, if I generate random 100,000 challenges and and run them through 1000 randomly generated XOR Arbiter PUFs, I can see some difference in the stdv between a 10 and 11 xor PUF. Not sure if this is supposed to be like that that.

```
from pypuf.simulation.delay import XORArbiterPUF
from pypuf.io import random_inputs

import numpy as np
import os


n = 64
numbTries = 100000

sum = 0
nnMat = np.ones((2, n))
nnMat[1, -1] = -1
nnMat = np.tile(nnMat, (numbTries, 1))



x = random_inputs(n, numbTries, int.from_bytes(os.urandom(4), "big"))

xv = np.repeat(x, 2, axis=0)
xv =  xv * nnMat

out = np.zeros((1000, 2))

for i in range(1000):
    puf = XORArbiterPUF(n, 10, int.from_bytes(os.urandom(4), "big"))
    PufSample = puf.eval(xv)
    out[i,0] = np.sum(PufSample[::2] - PufSample[1::2]) 

    puf = XORArbiterPUF(n, 11, int.from_bytes(os.urandom(4), "big"))
    PufSample = puf.eval(xv)
    out[i, 1] = np.sum(PufSample[::2] - PufSample[1::2])
    print(i/1000)
    
print(out.mean(0))
print(np.sqrt(out.var(0)))    

#output
#first try:
#[-5.914 -0.356],
#[343.02966141 512.50586852]

#second try
#[-27.804   8.234]
#[342.8475136  544.94524243]
```
If you can explain this away, I'm content with the fix.

**Comment by nils-wisiol** [comment]
I believe what you're seeing an effect related to what is described in https://eprint.iacr.org/2019/1091. As evidence, I've extended your loop to consider 8-, 9-, 10-, and 11-XOR Arbiter PUFs and received (with 100 samples):

```
[ 13.6  -44.     9.6   43.56]
[344.12265255 525.91816854 339.38096588 585.99109754]
```

**Comment by RRasche** [comment]
Alright. That makes sense. Should I close the issue then?
