### ISSUE TITLE
Question  about puf.val

### ISSUE THREAD

**Issue by weber-tsao** [nils-wisiol/pypuf#176]
Hello, I have some questions about puf.val():
When using puf.val() on XOR puf and lightweight secure puf, I know that it is the product of individual delays. However, I have two questions about it:

1. Is the value of puf.val for both XOR and lightweight secure puf means the product of individual delays?

2. The value of puf.val for both XOR and lightweight secure puf is not delayed difference, is that correct?

3. Why for XOR and lightweight secure puf, the delay difference is calculated by multiplication, but for arbiter puf, it is summation?

4. Both XOR and lightweight secure puf is constructed by multiple pufs in this case, how is the product individual delays calculated? Is that the product of all the pufs or just one of them? or did I misunderstand the structure of those pufs?

5. How is the product of individual delays calculated, I would like to know the basic idea about it, like what is needed to derive the value......

Can you help me with those questions? Thank you so much!

**Comment by nils-wisiol** [comment]
> 1. Is the value of puf.val for both XOR and lightweight secure puf means the product of individual delays?
> 2. The value of puf.val for both XOR and lightweight secure puf is not delayed difference, is that correct?


The value of `XORArbiterPUF.val` is the product of the individual delays. Example:

```python
import pypuf.simulation, pypuf.io

def noop(x):
    return x

puf = pypuf.simulation.XORArbiterPUF(n=64, k=4, seed=1)
challenge = pypuf.io.random_inputs(n=64, N=3, seed=2)

print("delay difference product\n", puf.val(challenge), "\n")

puf.combiner = noop

print("delay difference individually\n", puf.val(challenge), "\n")

print("delay difference individually, then multiplied\n", puf.val(challenge).prod(axis=1), "\n")
```

Will generate:

```
delay difference product
 [ -589.80384317   117.69841502 -8331.56422373] 

delay difference individually
 [[  8.25650626 -11.15455232  -4.55882146  -1.40477431]
 [  1.68773838 -18.17639299  -1.28805071   2.97868667]
 [-17.85821015 -16.13744569  -8.64238961   3.34518378]] 

delay difference individually, then multiplied
 [ -589.80384317   117.69841502 -8331.56422373] 
```

As you can see, the first and third output are identical. The same can be done for `LightweightSecurePUF`.

> 3. Why for XOR and lightweight secure puf, the delay difference is calculated by multiplication, but for arbiter puf, it is summation?
> 4. Both XOR and lightweight secure puf is constructed by multiple pufs in this case, how is the product individual delays calculated? Is that the product of all the pufs or just one of them? or did I misunderstand the structure of those pufs?
> 5. How is the product of individual delays calculated, I would like to know the basic idea about it, like what is needed to derive the value......

For XOR Arbiter PUF and Lightweight Secure PUF, the final response bit is the XOR of `k` many individual response bits. While the individual response bits are computed by summation, the XOR of these bits is computed my multiplication (as for -1, 1 bit notation, XOR operation corresponds to multiplication of real numbers). For reference, please read https://pypuf.readthedocs.io/en/latest/simulation/delay.html and Appendix of https://eprint.iacr.org/2021/555.
