### ISSUE TITLE
Question about XOR arbiter PUF

### ISSUE THREAD

**Issue by weber-tsao** [nils-wisiol/pypuf#177]
Hello, for XOR arbiter PUF, I have some questions about it:

1. In pypuf, it said that XOR arbiter PUF consists of k Arbiter PUFs, are those Arbiter PUFs all different? or are they the same, I just want to clarify

2. In pypuf, we can get the delay difference for XOR arbiter PUF by using "puf.val(challenge)". However, I am thinking is the XOR arbiter PUF made up of a number of arbiter PUFs, which means that we can actually calculate the individual arbiter PUF's delay difference and multiply them to get the same value as "puf.val(challenge)", or is the XOR arbiter PUF is another object itself?

3. Also, I think the delay difference for xor or lightweight puf is usually not visible to attackers, is that correct? or is it possible to derive from the challenge bits?
Thank you!

**Comment by nils-wisiol** [comment]
1. Yes, the Arbiter PUFs in the XOR Arbiter PUF are chosen independently at random.
2. For performance reasons, the XOR Arbiter PUF is not an object "composed" of several Arbiter PUF objects. Delay values are computed using the LTFArray [as described in the code](https://github.com/nils-wisiol/pypuf/blob/main/pypuf/simulation/base.py#L90).
3. For Arbiter PUF and Lightweight Secure PUF, the delay difference cannot be derived from a single PUF response. However, it can be derived to a certain accuracy if several responses to the same challenge are known (and are noisy). Please refer to DV13 from the pypuf bibliography.
