### ISSUE TITLE
Question about light weight secure puf

### ISSUE THREAD

**Issue by weber-tsao** [nils-wisiol/pypuf#180]
Hello, I am trying to use the lightweight secure puf in pypuf, and I found that it only return 1 but response. In my understanding, the lightweight secure puf should return multiple bit response. Is it because I am using the lightweight secure puf in pypuf in the wrong way or the structure of the lightweight secure puf in pypuf is different? If it is different, can you give me some idea of how pypuf’s lightweight secure puf is constructed? Thank you

**Comment by nils-wisiol** [comment]
pypuf only contains the 1-bit version of the Lightweight Secure PUF, i.e. setting Q' = 1 for the [Output Network](http://www.aceslab.org/sites/default/files/Lightweight%20Secure%20PUFs_0.pdf) (Sec. IV.B). Other versions are not implemented. If you are interested in including them in pypuf, I'm happy to accept pull requests.

The reason why other versions are not included is that in [Breaking the Lightweight Secure PUF](https://eprint.iacr.org/2019/799.pdf), it is argued that versions of the PUF with more output bits are weaker than the version with just one output bit. However, also the 1-output-bit-version has been broken in that paper.
