### ISSUE TITLE
Some questions about lr2021.py

### ISSUE THREAD

**Issue by weber-tsao** [nils-wisiol/pypuf#183]
I am currently trying to understand lr2021.py in order to modify it and get the information I want: **The additive delay model final value** for every challenge. I think the value is exactly the final layer's output, but I am stuck on how to get it. Can you give me some idea on how to get it? Or if my original idea of trying to find the additive delay model's value by looking at the final layer's output is already wrong? Thank you

**Comment by nils-wisiol** [comment]
The model values can be extracted from the trained model using the [`keras_to_pypuf` function](https://github.com/nils-wisiol/pypuf/blob/9dee98b086f2866f46601d09d669495579de0f58/pypuf/attack/lr2021.py#L157). The reason this does not show in the docs is #174 :-(

Feel free to re-open if this was not the answer you are looking for.

**Comment by weber-tsao** [comment]
Sorry but I think that is not the answer I am looking for.
![image](https://user-images.githubusercontent.com/67998511/178243060-6f63ea91-8a68-4fd7-9cd2-143b261c6a4f.png)
