### ISSUE TITLE
Continued question from Issue #183

### ISSUE THREAD

**Issue by weber-tsao** [nils-wisiol/pypuf#184]
Hello, I cannot reopen #183, so I create a new issue. I think the answer you gave me is not really solving my question. My question is to try and find the approximate delay difference by using the lr2021 attack because I think going through the neuron network structure is the same as the delay difference calculation.

This is how I tried to get the approximate delay difference(the second last layer output):
![image](https://user-images.githubusercontent.com/67998511/178466432-0929d247-480a-47a2-91f1-dfbb536445fe.png)
The value of test_answer:
![image](https://user-images.githubusercontent.com/67998511/178466563-65bed997-04af-43dd-82cb-5f902bc70c75.png)

Do you think the value I get is the correct one? Because it is different from using this code:
![image](https://user-images.githubusercontent.com/67998511/178467327-2f0b71a0-b574-4918-840e-89b60c88d69a.png)
Using this code, I got values between -infinity and +infinity, but from the second image, I got values always between -1 and 1. And I am well aware that it is caused by the activation function. I tried to modify a lot of things such as getting the output from a different layers but I still failed. Can you give me some idea on how to get the delay difference from lr2021.py attack? Thank you so much

**Comment by nils-wisiol** [comment]
I have difficulty understanding the details of your question.

Please post a minimal example of your code, the result that you obtained, and the result that you expected. (Please post code as text so I can run it.) Then I will try to explain the difference of actual result and expected result.

Thanks!

**Comment by weber-tsao** [comment]
Thank you so much.
This is the code to replace fit function in lr2021.py.
[modified_lr2021.txt](https://github.com/nils-wisiol/pypuf/files/9093286/modified_lr2021.txt)

Then run the code like this:
attack = LRAttack2021(crp, seed=3, k=1, bs=1000, lr=.001, epochs=100)
        model, layer_output = attack.fit()
        array = layer_output.numpy()
        print("Array = ",array)

**Comment by weber-tsao** [comment]
![image](https://user-images.githubusercontent.com/67998511/178955748-7e3ecfb0-421d-47e8-a902-f934ff63f8e2.png)

**Comment by weber-tsao** [comment]
Yes, I understand. Sorry I did not finish typing on the previous comment. 

The code to run:

[Uploading example_code.txt…]()

**Comment by weber-tsao** [comment]
Thank you so much! So I suppose that the actual value is almost the same as the expected delay difference. Therefore, I think I can use the actual value to represent the approximate delay difference?

**Comment by weber-tsao** [comment]
Thank you for your help!
