### ISSUE TITLE
Incorporating temperature and voltage dependencies 

### ISSUE THREAD

**Issue by harjas-kaur** [nils-wisiol/pypuf#190]
hello, i am trying to incorporate temperature and voltage dependencies in to the library, i've made some small modifications to this but am stuck on how to test it. i am not very familiar with library development. any help would be great. thanks.

**Comment by nils-wisiol** [comment]
Happy to help out if there are any concrete questions. I'd start with a paper that describes the physical model under temperature changes. The Arbiter PUF model used in pypuf does not do that. The model is described at length in https://depositonce.tu-berlin.de/items/5b2f1c91-d569-46e1-963d-400a82a03a64

**Comment by harjas-kaur** [comment]
I have the model from a project, actually I'm incorporating some work from
more people in my college into the library, I will share what all I have
tried to change in the code so far and feel like it should work, but I'm
not that familiar with packaging python libraries etc. I will make a proper
document with what all I have and share it shortly.... Thank you so much
for reaching out!

**Comment by nils-wisiol** [comment]
yeah, feel free to open a pull request here!

**Comment by harjas-kaur** [comment]
Thanks, I will!

**Comment by harjas-kaur** [comment]
Hello, I have opened a pull request to the repository, i'm really sorry for
the slow progress, i am very busy with a lot of academic things and this is
a side project I started in my free time, i will be very grateful if you
could help me out with this.
Thanks!
