### ISSUE TITLE
LTFArray.val() does not honor bias

### ISSUE THREAD

**Issue by nils-wisiol** [nils-wisiol/pypuf#31]
When using an `LTFArray` with `bias`, it will be [inserted into the calculation in the `eval` method](https://github.com/nils-wisiol/pypuf/blob/10c991126ba2316a2d679f0eb5c42aa135c898f1/pypuf/simulation/arbiter_based/ltfarray.py#L222-L223). However, if using the `val` method, it will not be used at all, [as can bee seen from the code](https://github.com/nils-wisiol/pypuf/blob/10c991126ba2316a2d679f0eb5c42aa135c898f1/pypuf/simulation/arbiter_based/ltfarray.py#L226-L227).

**Comment by MrM0nkey** [comment]
Done in https://github.com/nils-wisiol/pypuf/pull/61 .
