### ISSUE TITLE
evaluate challenges: response=0; unpacking iterator

### ISSUE THREAD

**Issue by Chrism7** [nils-wisiol/pypuf#36]
`simulation.eval()` can return zero (if `val()` returns zero). But responses should not be zero.

    def eval(self, inputs):
        """
        evaluates a given list of challenges regarding bias
        :param x: list of challenges
        :return: list of responses
        """
        if self.bias:
            inputs = tools.iter_append_last(inputs, 1)
        return sign(self.val(inputs)) # <-----

    def val(self, inputs):
        return self.combiner(self.ltf_eval(self.transform(inputs, self.k)))

`tools.sample_inputs()` returns an iterator over arrays of challenges, while the common usage of those is to unpack them into a 2-d-array. Maybe we should maintain the iterator object instead of unpacking it for the purpose of runtime advantages.

    class TrainingSet():
        """
        Basic data structure to hold a collection of challenge response pairs.
        Note that this is, strictly speaking, not a set.
        """

        def __init__(self, instance, N):
            self.instance = instance
            self.challenges = array(list(sample_inputs(instance.n, N))) # <-----
            self.responses = instance.eval(self.challenges)
            self.N = N

**Comment by Chrism7** [comment]
@nils-wisiol , @MrM0nkey for your interest.

**Comment by nils-wisiol** [comment]
For the use with input transformations, the array needs to be explicitly stored in memory anyways. Therefore it doesn't seem like a big advantage to keep the iterator object. Maybe `tools.sample_inputs` should not return an iterator to begin with?
