### ISSUE TITLE
Simulation And Learning

### ISSUE THREAD

**Issue by MrM0nkey** [nils-wisiol/pypuf#5]
# Feature
The framework should be able to create a model with a eligible distribution.
It should be possible to apply input and output transformations on it.

# Implementation
 See [simulation.py](https://github.com/nils-wisiol/pypuf/blob/0c91ff04090541dedee57923262e1c90e61beacc/pypuf/simulation.py) for a good a approach. The structure misses the possibility to add a new simulation model in order to be compatible with the [learner.py](https://github.com/nils-wisiol/pypuf/blob/0c91ff04090541dedee57923262e1c90e61beacc/pypuf/learner.py).

**Comment by nils-wisiol** [comment]
basic CLI was added in 5148414cab35ddc57ac30f8fd7f15c97c0053430 in improved later
