### ISSUE TITLE
Refactor mv_num_of_votes.py

### ISSUE THREAD

**Issue by MrM0nkey** [nils-wisiol/pypuf#64]
The command line script ```mv_num_of_votes.py``` hard codes some experiment parameters.
This file should be reworked in order to be able to pass all experiment parameters.
I started to rework this file in c9031569cc19c1c49d54e44fb283e493b3e595fa but this did not satisfy tests at the moment and need some additional work.

**Comment by nils-wisiol** [comment]
Nice to have, but I think right now we don't need to have this.
