### ISSUE TITLE
Sölter learning

### ISSUE THREAD

**Issue by MrM0nkey** [nils-wisiol/pypuf#7]
# Feature
The framework should be able to execute [Sölters logistic regression learning algorithm](https://www.researchgate.net/publication/259580784_Cryptanalysis_of_electrical_PUFs_via_machine_learning_algorithms) on an arbitrary simulation of a puf.

**Comment by nils-wisiol** [comment]
closed per 5148414cab35ddc57ac30f8fd7f15c97c0053430
