### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by nils-wisiol** [nils-wisiol/pypuf#72]
wip with @maoswald 

- environment setup (virtualenv, polymath)
- more examples
- execute tests locally
- easier access

**Comment by MrM0nkey** [comment]
In order to prevent things like #70 I recommend to write test for the example code too.

**Comment by nils-wisiol** [comment]
[Already done](https://github.com/nils-wisiol/pypuf/commit/bdaf9bd219b61ac454266b4fb7ef0ca0813e2e05) :+1:
