### ISSUE TITLE
numpy automatic multithreading interferes with Experimenter

### ISSUE THREAD

**Issue by nils-wisiol** [nils-wisiol/pypuf#84]
numpy (at least in some configurations/compliations) [automatically multithreads](https://scipy.github.io/old-wiki/pages/ParallelProgramming) some functions like `dot`. On big machines, this yields a huge overload of work, as each of the, let's say, 64 worker processes spawns another 64 worker threads. Resulting load is 64 times as high as intended.

Ways to reproduce: with 6e1f120ed57d57360486732e9e97d1fff05feb03, run `input_trans_comparison.py -n 64 -k 5 -s 1 -m 0xbad -t lightweight_secure_original -N 250000 -i 1000`. Use `top` to monitor CPU usage, use `pstree -c $(whoami)` to monitor processes and threads (threads are shown in curly braces). There should only be two processes, one for logging, one for the single experiment we are running (`-s 1`).

Workaround: set the following environment variables: `OMP_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 MKL_NUM_THREADS=1`

I am assuming some users will benefit from automatic multithreading; in other cases (like the one above) it interferes with our experiment schedule.

@taudor @MrM0nkey What is a good course of action? Disable multithreading entirely? Disable only when using the Experimenter class?

**Comment by taudor** [comment]
I would suggest using multithreading in a controlled manner. We should have the overview how and when multithreading is used.
Regarding just dot: I'm seeing just two cases of usage and one of them is ltf_eval. If we are doing the switch to pypuf_helper, dot will be substituted by a C function that is much faster in the case of one thread execution (6cdda73e3ec16ca489a2570a9b84da909781bf6f).

**Comment by MrM0nkey** [comment]
I would recommand to disable automatic thread spwaning in multiprocessing szenarios e.g. Experimenter class only. I wonder why this was not recognized earlier.
