### ISSUE TITLE
pypuf Memory Consumption

### ISSUE THREAD

**Issue by taudor** [nils-wisiol/pypuf#89]
We should have a look at the memory consumption of pypuf, especially regarding the challenges. Right now the challenges are consisting of just the elements `-1` and `1`. The corresponding numpy arrays are created without a detailed specification of the data type of the array. According to the numpy reference [1] in that case the array is created using "the minimum type required to hold the objects in the sequence". I can only assume that this refers just to types like `int` and `float` and does not include the size of the type.
If I do not specify a type, I get on my computer only arrays with `dtypes` of size 64. I think we could reduce the memory consumption for the challenges to one eighth of the memory we need right now by stating the type `int8` within the array creation. That would require a more strict definition and checking of the input/output types of the functions.
Regarding the speed there should be no big difference between different integer types in our case. But that clearly depends also on the used hardware.

[1] https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.array.html

**Comment by nils-wisiol** [comment]
fixed by, among others, ad8fd85d88ff3819db1ffebeed89265587da02a5
